### ISSUE TITLE
Admin CSS not showing

### ISSUE THREAD

**Issue by reuf** [tianissimo/vagrant-puppet-django#5]
Hello,
I had a problem loading css for admins. This worked for me
https://askubuntu.com/questions/477271/how-to-solve-404-for-static-files-with-django-and-nginx/482271#482271
After static routes are set you need to execute:

``` bash
sudo python manage.py collectstatic
```

for admin css to be pulled into static directory...

**Comment by tianissimo** [comment]
Actually, I don't think it's an issue but I'll add it into the readme.
Thank you. I really appreciate your info.
