### ISSUE TITLE
Registering models with admin not showing in admin section

### ISSUE THREAD

**Issue by reuf** [tianissimo/vagrant-puppet-django#6]
I have an issue like this one:
https://groups.google.com/forum/#!topic/django-users/Ftmw612OzS4
http://grokbase.com/p/gg/django-users/12cvq2vbg8/no-polls-in-the-admin-page

and the guy says that the solution is:

"I found the issue. The issue appears to be in a template override for 
the Admin app that the upstream provider added. When this was moved 
out of the way, the standard template was loaded, and polls showed up."

I believe it has to do with nginx...
I also found this that may help:
http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html

Any ideas?

**Comment by tianissimo** [comment]
I just tried it myself with the fresh install of django and I could see my model in the admin page.
One thing I came across was that you need to manually reload/restart uwsgi service after you changed the code in the project. 

Try running `service uwsgi restart` and see if it works.

If not, it'd be better if you can show the content of your admin.py file.
